build:
  image: geppettoapps/node-flow-jspm:4.4.7
  environment:
    - NPM_CONFIG_LOGLEVEL=warn
  commands:
    - npm install
    - jspm install
    - bin/ci
cache:
  mount:
    - jspm_packages
    - node_modules
