build:
  image: node:4.4.7
  environment:
    - NPM_CONFIG_LOGLEVEL=warn
  commands:
    - apt-get -yqq update
    - apt-get -yqq install libelf-dev
    - npm install jspm@beta -g
    - npm install
    - jspm install
    - bin/test
cache:
  mount:
    - jspm_packages
    - node_modules
